spring.application.name=webProject



# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/cps_db
spring.datasource.username=cps
spring.datasource.password=cps
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# JWT Configuration
ak.jwt.base64-secret=TRrx3ZoD9xgevlM73MU8/ay9VO+8RJ7NjvFh5Ab0xoTsKzuPYwCOKDZugGYsVxroYRfP94DH6jBxBhFyBPaQQQ==
ak.jwt.access-token-validity-in-seconds=300000
ak.jwt.refresh-token-validity-in-seconds=300000
jwt.secret=lasdjasldhadslfjladsfladsfkllasdjasldhadslfjladsfladsfkllasdjasldhadslfjladsfladsfkllasdjasldhadslfjladsfladsfkl

# Multipart Configuration for Large Files (e.g., mp4)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Run Sample data
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

#debug
logging.level.org.springframework.security=DEBUG

# File storage absolute path
file.storage.avatars=uploads/avatars
file.storage.documents=uploads/documents
file.storage.media=uploads/media
file.storage.temp=uploads/temp
file.storage.thumbnails=uploads/thumbnails



# Use MailHog instead of Gmail
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=

# No authentication needed for MailHog
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false



# Cho phép swagger-ui
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# URL chính để mở Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html

# Nếu muốn chỉ định base package để scan API
springdoc.packages-to-scan=com.example.webProject